# Section 4.4.1 Application of the Treatment Effect Model to Analysis of Observational Data (SD & PS)

## Preparation

```{r message=F, warning=F, error=F}
library(haven)
library(sampleSelection)
library(gmodels)
library(tidyverse)

# load data
d <- haven::read_dta("data/Data_Chapter4/chpt4_1.dta") 

# rename
d1 <- d %>%
  rename(
    external3 = bc3_ept,
    internal3 = bc3_ipt
  ) 
```

## Treatment Effect

```{r message=FALSE, warning=FALSE}
## tm1: external3
tm1 <- sampleSelection::treatReg(aodserv ~ cgrage1 + cgrage2 + cgrage3 + high + bahigh +
  employ + open + sexual + provide + supervis + other + cra47a +
  mental + arrest + psh17a + cidi + cgneed,
external3 ~ aodserv + black + hispanic + natam + chdage2 + chdage3 + ra,
data = d1
)
summary(tm1)

## tm2: internal3
tm2 <- sampleSelection::treatReg(aodserv ~ cgrage1 + cgrage2 + cgrage3 + high + bahigh +
  employ + open + sexual + provide + supervis + other + cra47a +
  mental + arrest + psh17a + cidi + cgneed,
internal3 ~ aodserv + black + hispanic + natam + chdage2 + chdage3 + ra,
data = d1
)
summary(tm2)

## tm3: To request Inverse Mill’s Ratio
myprobit <- glm(aodserv ~ cgrage1 + cgrage2 + cgrage3 + high + bahigh +
  employ + open + sexual + provide + supervis + other + cra47a +
  mental + arrest + psh17a + cidi + cgneed,
family = binomial(link = "probit"),
data = d1
)

d1 <- d1 %>%
  mutate(IMR = ifelse(aodserv == 0, -sampleSelection::invMillsRatio(myprobit)$IMR0, sampleSelection::invMillsRatio(myprobit)$IMR1))

head(d1$IMR, n = 10)
d1 %>%
  summarize(obs = n(),
            mean = mean(IMR),
            sd = sd(IMR),
            min = min(IMR),
            max = max(IMR), .groups = "drop")

# To check saved statistics
tm1 <- sampleSelection::treatReg(aodserv ~ cgrage1 + cgrage2 + cgrage3 + high + bahigh +
  employ + open + sexual + provide + supervis + other + cra47a +
  mental + arrest + psh17a + cidi + cgneed,
external3 ~ aodserv + black + hispanic + natam + chdage2 + chdage3 + ra,
data = d1
)
summary(tm1)
```

## Bivariate t-test

```{r message=FALSE, warning=FALSE}
test1 <- t.test(external3 ~ aodserv, data = d1, var.eq = TRUE)
broom::tidy(test1)
test2 <- t.test(internal3 ~ aodserv, data = d1, var.eq = TRUE)
broom::tidy(test2)
```

## Regression Control

```{r message=FALSE, warning=FALSE}
## external
lm1 <- lm(external3 ~ aodserv + black + hispanic + natam + chdage2 + chdage3 + ra +
  cgrage1 + cgrage2 + cgrage3 + high + bahigh +
  employ + open + sexual + provide + supervis + other + cra47a +
  mental + arrest + psh17a + cidi + cgneed,
data = d1
)
summary(lm1)

## internal
lm2 <- lm(internal3 ~ aodserv + black + hispanic + natam + chdage2 + chdage3 + ra +
  cgrage1 + cgrage2 + cgrage3 + high + bahigh +
  employ + open + sexual + provide + supervis + other + cra47a +
  mental + arrest + psh17a + cidi + cgneed,
data = d1
)
summary(lm2)
```

## Sample Description

```{r message=FALSE, warning=FALSE}
## race aodserv
d2 <- d1 %>%
  select(aodserv, black, hispanic, natam) %>%
  mutate(race = case_when(
    black == 1 ~ 2,
    hispanic == 1 ~ 3,
    natam == 1 ~ 4,
    TRUE ~ 1
  ))

gmodels::CrossTable(d2$race, d2$aodserv, prop.t = FALSE, prop.chisq = FALSE, chisq = TRUE)

## age aodserv
d3 <- d1 %>%
  select(aodserv, chdage2, chdage3) %>%
  mutate(age = case_when(
    chdage2 == 1 ~ 1,
    chdage3 == 1 ~ 2,
    TRUE ~ 3
  ))

gmodels::CrossTable(d3$age, d3$aodserv, prop.t = FALSE, prop.chisq = FALSE, chisq = TRUE)

## ra aodserv
CrossTable(d1$ra, d1$aodserv, prop.t = FALSE, prop.chisq = FALSE, chisq = TRUE)

## cgage aodserv
d4 <- d1 %>%
  select(aodserv, cgrage1, cgrage2, cgrage3) %>%
  mutate(cgage = case_when(
    cgrage1 == 1 ~ 1,
    cgrage2 == 1 ~ 2,
    cgrage3 == 1 ~ 3,
    TRUE ~ 4
  ))

CrossTable(d4$cgage, d4$aodserv, prop.t = FALSE, prop.chisq = FALSE, chisq = TRUE)

## cgedu aodserv
d5 <- d1 %>%
  select(aodserv, high, bahigh) %>%
  mutate(cgedu = case_when(
    high == 1 ~ 2,
    bahigh == 1 ~ 3,
    TRUE ~ 1
  ))

CrossTable(d5$cgedu, d5$aodserv, prop.t = FALSE, prop.chisq = FALSE, chisq = TRUE)

## employ aodserv
CrossTable(d1$employ, d1$aodserv, prop.t = FALSE, prop.chisq = FALSE, chisq = TRUE)

## open aodserv
CrossTable(d1$open, d1$aodserv, prop.t = FALSE, prop.chisq = FALSE, chisq = TRUE)

## mtype aodserv
d6 <- d1 %>%
  select(aodserv, sexual, provide, supervis, other) %>%
  mutate(mytype = case_when(
    sexual == 1 ~ 2,
    provide == 1 ~ 3,
    supervis == 1 ~ 4,
    other == 1 ~ 5,
    TRUE ~ 1
  ))

CrossTable(d6$mytype, d6$aodserv, prop.t = FALSE, prop.chisq = FALSE, chisq = TRUE)

## cra47a aodserv
CrossTable(d1$cra47a, d1$aodserv, prop.t = FALSE, prop.chisq = FALSE, chisq = TRUE)

## mental aodserv
CrossTable(d1$mental, d1$aodserv, prop.t = FALSE, prop.chisq = FALSE, chisq = TRUE)

## arrest aodserv
CrossTable(d1$arrest, d1$aodserv, prop.t = FALSE, prop.chisq = FALSE, chisq = TRUE)

## psh17a aodserv
CrossTable(d1$psh17a, d1$aodserv, prop.t = FALSE, prop.chisq = FALSE, chisq = TRUE)

## cidi aodserv
CrossTable(d1$cidi, d1$aodserv, prop.t = FALSE, prop.chisq = FALSE, chisq = TRUE)

## cgneed aodserv
CrossTable(d1$cgneed, d1$aodserv, prop.t = FALSE, prop.chisq = FALSE, chisq = TRUE)
```
