# Section 11.5.1 & 11.5.2 Sensitivity Analysis of the Effects (SD & PS)

## Section 11.5.1 Sensitivity Analysis of the Effects

Example from `rbounds`:^[https://cran.r-project.org/web/packages/rbounds/rbounds.pdf]

```{r message=F, warning=F, error=F}
library(rbounds)
library(coin)
library(tidyverse)
```

```{r message=FALSE, warning=FALSE}
# Data: Matched Data of Lead Blood Levels in Children
trt <- c(38, 23, 41, 18, 37, 36, 23, 62, 31, 34, 24, 14, 21, 17, 16, 20, 15, 10, 45, 39, 22, 35, 49, 48, 44, 35, 43, 39, 34, 13, 73, 25, 27)

ctrl <- c(16, 18, 18, 24, 19, 11, 10, 15, 16, 18, 18, 13, 19, 10, 16, 16, 24, 13, 9, 14, 21, 19, 7, 18, 19, 12, 11, 22, 25, 16, 13, 11, 13)
```

```{r message=FALSE, warning=FALSE}
p <- rbounds::psens(trt, ctrl, GammaInc = 0.01)
p$bounds %>%
  filter(Gamma %in% c(1:4, 4.25, 5:6))

h <- rbounds::hlsens(trt, ctrl, GammaInc = 0.01)
h$bounds %>%
  filter(Gamma %in% c(1:4, 4.25, 5:6))
```

## Section 11.5.2 Sensitivity Analysis & Pair Matching

```{r message=FALSE, warning=FALSE}
d <- haven::read_dta("data/Data_Chapter11/chpt5_2.dta")

# kuse == 1
d1 <- d  %>%
  filter(kuse == 1) %>% 
  dplyr::select(pm, kuse, y1 = lwss97) 

# kuse == 0
d0 <- d %>%
  filter(kuse == 0) %>% 
  dplyr::select(pm, kuse, y0 = lwss97)
  
# merge data
d2 <- left_join(d0, d1, "pm") %>% 
  na.omit(y1, y0) 
```

```{r message=FALSE, warning=FALSE}
# Notice that the direction of some results from the rbounds::psens() function may need to be reversed to obtain the same results as Stata's rbounds module.

p1 <- rbounds::psens(d2$y1, d2$y0, GammaInc = 0.01)
p1$bounds %>%
  filter(Gamma %in% c(1, 1.3, 1.42, 1.43, 1.44, 1.45, 1.5, 2)) %>% 
  mutate(`Lower bound` = 1 - `Lower bound`,
         `Upper bound` = 1 - `Upper bound`)

h1 <- rbounds::hlsens(d2$y1, d2$y0, GammaInc = 0.01)
h1$bounds %>%
  filter(Gamma %in% c(1, 1.3, 1.42, 1.43, 1.44, 1.45, 1.5, 2))
```

```{r message=FALSE, warning=FALSE}
coin::wilcoxsign_test(y1 ~ y0, data = d2)
```
